sudo: false
language: node_js
cache:
  bundler: true
  directories:
    - node_modules
notifications:
  flowdock: e7454f5285e7b9ab67009802d5560490
node_js:
- '0.10'
deploy:
  provider: npm
  skip_cleanup: true
  clean_up: false
  email: serveradmin@octoblu.com
  api_key:
    secure: U617xKK4QrU98MMzDmAZrlhV0vqcH3mbJvZPYJGoYCbm/PAaA5NtBbaNd+CH0jP1EDItzk2vpjQw2o8tYBh1l1qGSDtOnRARR9AYZShwVdACbItuFvAn+MzMMKPcal2CnKOt6h4YWQuc4O9TDTL/K53jxRknW3EdhQ1TMkMv0NA=
  on:
    tags: true
    all_branches: true
addons:
  code_climate:
    repo_token: 95986ecafdc6a839cf3f7ad924918e1b652c53f28d9f49666bd614d128c6e227
after_script:
  - cat coverage/lcov.info | codeclimate
