sudo: false
language: shell
os:
- linux
- osx
addons:
  code_climate:
    repo_token: 95986ecafdc6a839cf3f7ad924918e1b652c53f28d9f49666bd614d128c6e227
before_script:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then npm install -g codeclimate-test-reporter; fi
after_script:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; codeclimate-test-reporter < coverage/lcov.info; fi
cache:
  bundler: true
  directories:
  - node_modules
matrix:
  allow_failures:
  - os: osx
install:
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install nvm; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then source $(brew --prefix nvm)/nvm.sh; fi
- nvm install v0.10
- npm install npm -g
- npm install
script:
- if [ "$TRAVIS_OS_NAME" != "osx" ]; then npm test; fi
after_success:
- mkdir -p dpl_s3
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then .installer/darwin/build; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then mkdir -p dpl_s3/latest; cp .installer/darwin/cache/GatebluService.pkg
  dpl_s3/latest; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then mkdir -p dpl_s3/${TRAVIS_TAG:-$TRAVIS_COMMIT};
  cp .installer/darwin/cache/GatebluService.pkg dpl_s3/${TRAVIS_TAG:-$TRAVIS_COMMIT};
  fi
deploy:
- provider: s3
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key:
    secure: lKdRL6iXGHk9JZde8f2gzfZUtmsJB1QdT9W+x4FFWtcdtkZ66+nXc4VWbCzk6l5B42xgq63Lc0k31T/NZf9t2GJgoWPGFA5lNuDCR2/DBb5Yc+DywUiuVMEdUPqf2JRdg3QIzetgyVEZykqpcGOMhnCQTk9xGOGmKz+msbeLE9s=
  bucket: gateblu
  upload-dir: gateblu-service
  region: us-west-2
  skip_cleanup: true
  local-dir: dpl_s3
  on:
    tags: true
    all_branches: master
- provider: npm
  skip_cleanup: true
  clean_up: false
  email: serveradmin@octoblu.com
  api_key:
    secure: "JrtrtwcLrsQJWPfv0KIZVIcwUT7GkxnK5Xpe+vptEzcgtjCGw2IyUNJFK+vf+A2uoSn+qzVKtNhn8ygxXICw9ZKV+IycLrN+NjDrCcoCAOlPhZjOKqTWISWujIoo4HpNIvn+WxD5GiOXtjPxmu6IkWUzWRAj8iplqx3wzLYH5J0="
  on:
    tags: true
    branches: true
env:
  global:
    secure: N6cxPy+LiLrHpSnbZnSlR5EIlDEDI0++aVZln9YBOi55SNFf9pP8Aqa4PkkKgWSbO8RRgQRBndzuDZ+uU8zxuhv2T55OUh0M9/oR9LhQAv4xGNryBvo3pjhCO3G213M8lBsEoD8bfHeBTgyBdld3Y2N/XzSeSzPPlbR3YMbltX0=
