sudo: false
language: shell
os:
- linux
- osx
cache:
  bundler: true
  directories:
  - node_modules
matrix:
  allow_failures:
  - os: osx
install:
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install nvm; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then source $(brew --prefix nvm)/nvm.sh; fi
- nvm install v0.10
- npm install
script:
- if [ "$TRAVIS_OS_NAME" != "osx" ]; then npm test; fi
after_success:
- mkdir -p dpl_s3
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then .installer/darwin/build; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then mkdir -p dpl_s3/latest; cp .installer/darwin/cache/GatebluService.pkg
  dpl_s3/latest; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then mkdir -p dpl_s3/${TRAVIS_TAG:-$TRAVIS_COMMIT};
  cp .installer/darwin/cache/GatebluService.pkg dpl_s3/${TRAVIS_TAG:-$TRAVIS_COMMIT};
  fi
deploy:
  - provider: s3
    access_key_id: AKIAJH2D5IPIRHYJT5IA
    secret_access_key:
      secure: h7TbBN4AqHuHR4nVfLUqgp04WJ9gWRcSLMTYsVT0fjhlRJM/2mKEqUtNHvAiKxVl1roZAQTQ1QhOYeDucDByiOjktcQs5v6iTnaGWyLvsU0z2NR0XcyhnPDXPWn9SV7tUrwKJwcOFhM61xQ6COjUZqbDA0meYd96EWGjvVwCNqo=
    bucket: gateblu
    upload-dir: gateblu-service
    region: us-west-2
    skip_cleanup: true
    local-dir: dpl_s3
    on:
      tags: true
      all_branches: master
addons:
  code_climate:
    repo_token: 95986ecafdc6a839cf3f7ad924918e1b652c53f28d9f49666bd614d128c6e227
after_script:
- cat coverage/lcov.info | codeclimate
env:
  global:
    secure: N6cxPy+LiLrHpSnbZnSlR5EIlDEDI0++aVZln9YBOi55SNFf9pP8Aqa4PkkKgWSbO8RRgQRBndzuDZ+uU8zxuhv2T55OUh0M9/oR9LhQAv4xGNryBvo3pjhCO3G213M8lBsEoD8bfHeBTgyBdld3Y2N/XzSeSzPPlbR3YMbltX0=
