platform:
  - x86
  - x64

build:
  parallel: true

matrix:
  fast_finish: true

artifacts:
  - path: '**\*.msi'
    name: GatebluService

build_script:
  - '.installer\win32-$(platform)\build.ps1'

deploy:
  - provider: S3
    access_key_id: AKIAIT4X4NDGM2WVL6VA
    secret_access_key:
      secure: J01/MZX00MKgxnFXoyiqoHSSwZbccuEfIUhw9yqRErCO0WWv/m3qDAqLe7RaN/E5
    bucket: gateblu
    folder: GatebluService
    artifact: GatebluService
    set_public: true
