platform:
  - x86
  - x64

build:
  parallel: true

matrix:
  fast_finish: true

artifacts:
  - path: '*.msi'
    name: GatebluService

build_script:
  - ps: >-
      if($env:platform -eq "x86") {
        . .\.installer\win32-ia32\build.ps1
      } else {
        . .\.installer\win32-x64\build.ps1
      }

after_build:
  - ps: >-
      mkdir $env:APPVEYOR_REPO_TAG_NAME
      cp '**\*.msi' $env:APPVEYOR_REPO_TAG_NAME\
  - ps: $root = Resolve-Path $env:APPVEYOR_REPO_TAG_NAME; [IO.Directory]::GetFiles($root.Path, '*.*', 'AllDirectories') | % { Push-AppveyorArtifact $_ -FileName $_.Substring($root.Path.Length + 1) -DeploymentName S3.GatebluService }

deploy:
  - provider: S3
    access_key_id: AKIAIT4X4NDGM2WVL6VA
    secret_access_key:
      secure: J01/MZX00MKgxnFXoyiqoHSSwZbccuEfIUhw9yqRErCO0WWv/m3qDAqLe7RaN/E5
    bucket: gateblu
    folder: GatebluService
    artifact: S3.GatebluService
    set_public: true
