platform:
  - x86
  - x64

build:
  parallel: true

cache:
  - .installer\win32-ia32\cache
  - .installer\win32-x64\cache

build_script:
  - ps: >-
      if($env:platform -eq "x86") {
        . .\.installer\win32-ia32\build.ps1
      } else {
        . .\.installer\win32-x64\build.ps1
      }

after_build:
  - ps: >-
      if($env:APPVEYOR_REPO_TAG_NAME){
        $env:TAG_NAME=$env:APPVEYOR_REPO_TAG_NAME
      } else {
        $env:TAG_NAME=$env:APPVEYOR_REPO_COMMIT
      }
  - ps: mkdir output\$env:TAG_NAME | Out-Null
  - ps: >-
      if($env:APPVEYOR_REPO_TAG_NAME){
        mkdir output\latest | Out-Null
      }
  - ps: cp '.\.installer\win32-*\output\*.msi' output\$env:TAG_NAME
  - ps: >-
      if($env:APPVEYOR_REPO_TAG_NAME){
        cp "output\$env:TAG_NAME\*" output\latest
      }
  - ps: $root = Resolve-Path output; [IO.Directory]::GetFiles($root.Path, '*.*', 'AllDirectories') | % { Push-AppveyorArtifact $_ -FileName $_.Substring($root.Path.Length + 1) -DeploymentName S3.GatebluService }

deploy:
  - provider: S3
    access_key_id: AKIAIT4X4NDGM2WVL6VA
    secret_access_key:
      secure: J01/MZX00MKgxnFXoyiqoHSSwZbccuEfIUhw9yqRErCO0WWv/m3qDAqLe7RaN/E5
    bucket: gateblu
    folder: gateblu-service
    artifact: S3.GatebluService
    set_public: true
    on:
      branch: atom-shell
      appveyor_repo_tag: true
